using System.Collections.Concurrent;
using System.Text;
using Microsoft.Extensions.Options;
using Orbita.Api.Options;

namespace Orbita.Api.Services;

public sealed record CrmSipRuntimeAccount(
    string Server,
    string Domain,
    int Port,
    string Transport,
    string SipLogin,
    string AuthorizationLogin,
    string Password,
    bool UseForOutbound,
    string AccountKey = "default",
    string Name = "Основная линия",
    string Mode = "shared",
    string OutboundCallerId = "");

public sealed record CrmSipRuntimeStatus(
    string Status,
    DateTime? CheckedAtUtc,
    string? Detail = null);

public sealed record CrmAsteriskRuntimeReceiver(Guid PublicId, string Secret);

public sealed record CrmAsteriskWebRtcEndpoint(
    string Extension,
    string AuthorizationUsername,
    string Password);

public sealed class CrmSipRuntimeConfigWriter(IOptions<CrmSipRuntimeOptions> configuredOptions)
{
    private readonly CrmSipRuntimeOptions _options = configuredOptions.Value;
    private readonly ConcurrentDictionary<string, SemaphoreSlim> _writeLocks =
        new(StringComparer.Ordinal);

    public bool IsAvailable => !string.IsNullOrWhiteSpace(_options.ConfigPath);

    public async Task<(bool Success, string? Error)> WriteBeelineAsync(
        Guid officeId,
        CrmSipRuntimeAccount account,
        CancellationToken ct = default) =>
        await WriteBeelineAccountsAsync(officeId, [account with { AccountKey = "default" }], ct);

    public async Task<(bool Success, string? Error)> WriteBeelineAccountsAsync(
        Guid officeId,
        IReadOnlyCollection<CrmSipRuntimeAccount> accounts,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return (false, "Каталог runtime-конфигурации SIP-сервера не настроен.");
        }

        var unsafeValue = accounts.Any(account => new[]
            {
                account.Server,
                account.Domain,
                account.Transport,
                account.SipLogin,
                account.AuthorizationLogin,
                account.Password,
                account.AccountKey
            }.Any(ContainsAsteriskControlCharacter));
        if (unsafeValue)
        {
            return (false, "Реквизиты содержат недопустимые управляющие символы.");
        }

        var officeKey = officeId.ToString("D");
        Directory.CreateDirectory(_options.ConfigPath);
        var configPath = Path.Combine(_options.ConfigPath, $"beeline.{officeKey}.conf");
        var outboundPath = Path.Combine(_options.ConfigPath, $"beeline.{officeKey}.outbound");
        var accountsPath = Path.Combine(_options.ConfigPath, $"beeline.{officeKey}.accounts");
        if (accounts.Any(account => !IsValidAccountKey(account.AccountKey))
            || accounts.GroupBy(account => account.AccountKey, StringComparer.OrdinalIgnoreCase).Any(group => group.Count() > 1))
        {
            return (false, "Идентификаторы SIP-линий некорректны или повторяются.");
        }

        var normalizedAccounts = accounts
            .OrderBy(account => account.AccountKey, StringComparer.Ordinal)
            .ToList();
        var configBuilder = new StringBuilder("; Generated by Orbita. Do not edit inside the container.\n");
        foreach (var account in normalizedAccounts)
        {
            // Beeline rejects requests carrying a SIP Route header. Send directly to the
            // regional SIP server while keeping Domain as the subscriber identity domain.
            var endpointKey = GetEndpointKey(officeId, account.AccountKey);
            var registrar = account.Server;
            configBuilder.AppendLine($$"""
            ; {{account.Name}} ({{account.Mode}})
            [beeline-{{endpointKey}}-auth]
            type=auth
            auth_type=userpass
            username={{account.AuthorizationLogin}}
            password={{account.Password}}

            [beeline-{{endpointKey}}-aor]
            type=aor
            contact=sip:{{registrar}}:{{account.Port}}
            ; Beeline Cloud PBX does not support SIP OPTIONS and answers 403 to probes.
            qualify_frequency=0

            [beeline-{{endpointKey}}]
            type=endpoint
            transport=transport-{{account.Transport}}
            context=from-orbita-provider
            disallow=all
            allow=alaw,ulaw
            outbound_auth=beeline-{{endpointKey}}-auth
            aors=beeline-{{endpointKey}}-aor
            from_user={{account.SipLogin}}
            from_domain={{account.Domain}}
            direct_media=no
            rtp_symmetric=yes
            force_rport=yes
            rewrite_contact=yes
            dtmf_mode=rfc4733
            set_var=ORBITA_OFFICE_ID={{officeKey}}

            [beeline-{{endpointKey}}-registration]
            type=registration
            transport=transport-{{account.Transport}}
            outbound_auth=beeline-{{endpointKey}}-auth
            server_uri=sip:{{registrar}}:{{account.Port}}
            client_uri=sip:{{account.SipLogin}}@{{account.Domain}}
            contact_user={{account.SipLogin}}
            line=yes
            endpoint=beeline-{{endpointKey}}
            retry_interval=60
            forbidden_retry_interval=300
            expiration=120
            """);
        }

        var defaultAccount = normalizedAccounts.FirstOrDefault(account => account.UseForOutbound);
        var outboundEndpoint = defaultAccount is null
            ? "primary"
            : defaultAccount.AccountKey == "default"
                ? "beeline"
                : $"beeline-{GetEndpointKey(officeId, defaultAccount.AccountKey)}";
        var accountIndex = string.Join('\n', normalizedAccounts.Select(account =>
            $"{account.AccountKey}=beeline-{GetEndpointKey(officeId, account.AccountKey)}-registration"));
        await WriteAtomicallyAsync(configPath, configBuilder.ToString(), ct);
        await WriteAtomicallyAsync(accountsPath, accountIndex.Length == 0 ? string.Empty : accountIndex + "\n", ct);
        await WriteAtomicallyAsync(outboundPath, outboundEndpoint + "\n", ct);
        return (true, null);
    }

    public async Task<(bool Success, string? Error)> WritePlusofonAsync(
        Guid officeId,
        CrmSipRuntimeAccount account,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return (false, "Каталог runtime-конфигурации SIP-сервера не настроен.");
        }

        var unsafeValue = new[]
        {
            account.Server,
            account.Domain,
            account.Transport,
            account.SipLogin,
            account.AuthorizationLogin,
            account.Password,
            account.OutboundCallerId
        }.Any(ContainsAsteriskControlCharacter);
        if (unsafeValue)
        {
            return (false, "Реквизиты содержат недопустимые управляющие символы.");
        }

        var officeKey = officeId.ToString("D");
        var endpointKey = GetEndpointKey(officeId);
        Directory.CreateDirectory(_options.ConfigPath);
        var configPath = Path.Combine(_options.ConfigPath, $"plusofon.{officeKey}.conf");
        var callerIdPath = Path.Combine(_options.ConfigPath, $"plusofon.{officeKey}.callerid");
        var config = $$"""
            ; Generated by Orbita. Do not edit inside the container.
            [plusofon-{{endpointKey}}-auth]
            type=auth
            auth_type=userpass
            username={{account.AuthorizationLogin}}
            password={{account.Password}}

            [plusofon-{{endpointKey}}-aor]
            type=aor
            contact=sip:{{account.Server}}:{{account.Port}}
            qualify_frequency=30

            [plusofon-{{endpointKey}}]
            type=endpoint
            transport=transport-{{account.Transport}}
            context=from-orbita-provider
            disallow=all
            allow=alaw,ulaw
            outbound_auth=plusofon-{{endpointKey}}-auth
            aors=plusofon-{{endpointKey}}-aor
            from_user={{account.SipLogin}}
            from_domain={{account.Domain}}
            sdp_owner={{account.SipLogin}}
            direct_media=no
            ice_support=no
            send_rpid=yes
            rtp_symmetric=yes
            force_rport=yes
            rewrite_contact=yes
            timers=no
            dtmf_mode=rfc4733
            set_var=ORBITA_OFFICE_ID={{officeKey}}

            [plusofon-{{endpointKey}}-identify]
            type=identify
            endpoint=plusofon-{{endpointKey}}
            match=185.54.49.80
            match=185.54.49.83

            [plusofon-{{endpointKey}}-registration]
            type=registration
            transport=transport-{{account.Transport}}
            outbound_auth=plusofon-{{endpointKey}}-auth
            server_uri=sip:{{account.Server}}:{{account.Port}}
            client_uri=sip:{{account.SipLogin}}@{{account.Domain}}
            contact_user={{account.SipLogin}}
            line=yes
            endpoint=plusofon-{{endpointKey}}
            retry_interval=60
            forbidden_retry_interval=300
            expiration=300
            auth_rejection_permanent=yes
            """;

        await WriteAtomicallyAsync(configPath, config + Environment.NewLine, ct);
        await WriteAtomicallyAsync(
            callerIdPath,
            account.OutboundCallerId + "\n" + account.Domain + "\n",
            ct);
        await WriteOutboundSelectionAsync(
            officeId,
            Orbita.Contracts.CrmTelephonyProviders.Plusofon,
            account.UseForOutbound,
            ct);
        return (true, null);
    }

    public async Task<(bool Success, string? Error)> WriteAsteriskReceiverAsync(
        Guid officeId,
        CrmAsteriskRuntimeReceiver receiver,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return (false, "Каталог runtime-конфигурации SIP-сервера не настроен.");
        }
        if (receiver.PublicId == Guid.Empty
            || string.IsNullOrWhiteSpace(receiver.Secret)
            || receiver.Secret.Length > 512
            || receiver.Secret.Any(character => character is '\r' or '\n' or '='))
        {
            return (false, "Некорректные реквизиты приёмника SIP-сервера.");
        }

        Directory.CreateDirectory(_options.ConfigPath);
        var path = Path.Combine(_options.ConfigPath, $"receiver.{officeId:D}.conf");
        var content = $"public_id={receiver.PublicId:D}\nsecret={receiver.Secret}\n";
        await WriteAtomicallyAsync(path, content, ct);
        return (true, null);
    }

    public Task<CrmSipRuntimeStatus> ReadBeelineStatusAsync(
        Guid officeId,
        string accountKey = "default",
        CancellationToken ct = default) =>
        ReadProviderStatusAsync(officeId, Orbita.Contracts.CrmTelephonyProviders.Beeline, accountKey, ct);

    public Task<CrmSipRuntimeStatus> ReadPlusofonStatusAsync(
        Guid officeId,
        CancellationToken ct = default) =>
        ReadProviderStatusAsync(officeId, Orbita.Contracts.CrmTelephonyProviders.Plusofon, "default", ct);

    private async Task<CrmSipRuntimeStatus> ReadProviderStatusAsync(
        Guid officeId,
        string provider,
        string accountKey,
        CancellationToken ct)
    {
        if (!IsAvailable)
        {
            return new CrmSipRuntimeStatus("runtime-unavailable", null);
        }

        var path = Path.Combine(_options.ConfigPath, $"{provider}.{officeId:D}.status");
        if (!File.Exists(path))
        {
            return new CrmSipRuntimeStatus("pending", null);
        }

        try
        {
            var lines = await File.ReadAllLinesAsync(path, ct);
            var statusLine = lines.FirstOrDefault(line => line.StartsWith($"{accountKey}=", StringComparison.OrdinalIgnoreCase));
            var status = statusLine is null
                ? "pending"
                : statusLine[(statusLine.IndexOf('=') + 1)..].Trim().ToLowerInvariant();
            var detailLine = lines.FirstOrDefault(line => line.StartsWith(
                $"{accountKey}.detail=", StringComparison.OrdinalIgnoreCase));
            var detail = detailLine is null
                ? null
                : detailLine[(detailLine.IndexOf('=') + 1)..].Trim();
            if (string.IsNullOrWhiteSpace(detail) || detail.Length > 128)
            {
                detail = null;
            }
            var checkedAtLine = lines.LastOrDefault();
            var checkedAt = lines.Length > 1 && DateTime.TryParse(
                checkedAtLine,
                null,
                System.Globalization.DateTimeStyles.RoundtripKind,
                out var parsed)
                ? parsed.ToUniversalTime()
                : (DateTime?)null;
            return new CrmSipRuntimeStatus(
                string.IsNullOrWhiteSpace(status) ? "unknown" : status,
                checkedAt,
                detail);
        }
        catch (IOException)
        {
            return new CrmSipRuntimeStatus("pending", null);
        }
    }

    public async Task WriteUserOutboundRoutesAsync(
        Guid officeId,
        IReadOnlyDictionary<string, string> routes,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return;
        }

        Directory.CreateDirectory(_options.ConfigPath);
        var path = Path.Combine(_options.ConfigPath, $"routes.{officeId:D}.conf");
        var content = string.Join(
            '\n',
            routes
                .Where(x => x.Key.Length is > 0 and <= 8 && x.Key.All(char.IsDigit))
                .OrderBy(x => x.Key, StringComparer.Ordinal)
                .Select(x => $"{x.Key}={NormalizeOutboundProvider(officeId, x.Value)}"));
        await WriteAtomicallyAsync(path, content.Length == 0 ? string.Empty : content + "\n", ct);
    }

    public async Task<(bool Success, string? Error)> WriteWebRtcEndpointsAsync(
        Guid officeId,
        IReadOnlyCollection<CrmAsteriskWebRtcEndpoint> endpoints,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return (false, "Каталог runtime-конфигурации SIP-сервера не настроен.");
        }

        if (endpoints.Any(endpoint =>
                endpoint.Extension.Length is < 1 or > 8
                || !endpoint.Extension.All(char.IsDigit)
                || endpoint.AuthorizationUsername.Length is < 1 or > 128
                || !endpoint.AuthorizationUsername.All(character =>
                    char.IsAsciiLetterOrDigit(character) || character is '-' or '_')
                || endpoint.Password.Length is < 16 or > 512
                || ContainsAsteriskControlCharacter(endpoint.Password))
            || endpoints.GroupBy(endpoint => endpoint.Extension, StringComparer.OrdinalIgnoreCase)
                .Any(group => group.Count() > 1)
            || endpoints.GroupBy(endpoint => endpoint.AuthorizationUsername, StringComparer.OrdinalIgnoreCase)
                .Any(group => group.Count() > 1))
        {
            return (false, "Реквизиты браузерной SIP-линии некорректны или повторяются.");
        }

        var content = new StringBuilder("; Generated by Orbita. Do not edit inside the container.\n");
        foreach (var endpoint in endpoints.OrderBy(endpoint => endpoint.Extension, StringComparer.Ordinal))
        {
            content.AppendLine($$"""

            [{{endpoint.AuthorizationUsername}}]
            type=aor
            max_contacts=1
            remove_existing=yes
            support_path=yes
            qualify_frequency=30

            [{{endpoint.AuthorizationUsername}}-auth]
            type=auth
            auth_type=userpass
            username={{endpoint.AuthorizationUsername}}
            password={{endpoint.Password}}

            [{{endpoint.AuthorizationUsername}}]
            type=endpoint
            transport=transport-ws
            context=from-orbita-managers
            disallow=all
            allow=ulaw,alaw
            auth={{endpoint.AuthorizationUsername}}-auth
            aors={{endpoint.AuthorizationUsername}}
            callerid={{endpoint.Extension}} <{{endpoint.Extension}}>
            webrtc=yes
            dtls_auto_generate_cert=yes
            direct_media=no
            rtp_symmetric=yes
            force_rport=yes
            rewrite_contact=yes
            dtmf_mode=rfc4733
            """);
        }

        Directory.CreateDirectory(_options.ConfigPath);
        var path = Path.Combine(_options.ConfigPath, $"webrtc.{officeId:D}.conf");
        await WriteAtomicallyAsync(path, content.ToString(), ct);
        return (true, null);
    }

    private static string NormalizeOutboundProvider(Guid officeId, string? provider)
    {
        if (string.Equals(provider, Orbita.Contracts.CrmTelephonyProviders.Beeline, StringComparison.OrdinalIgnoreCase))
        {
            return Orbita.Contracts.CrmTelephonyProviders.Beeline;
        }
        if (Orbita.Contracts.CrmTelephonyOutboundProviders.TryGetBeelineLineKey(provider, out var accountKey))
        {
            // The original single Beeline account is stored as `default` and its
            // Asterisk endpoint keeps the legacy office-scoped name.  Preserve
            // the legacy route token so the watcher resolves it correctly.
            if (string.Equals(accountKey, "default", StringComparison.OrdinalIgnoreCase))
            {
                return Orbita.Contracts.CrmTelephonyProviders.Beeline;
            }
            return $"beeline-{GetEndpointKey(officeId, accountKey)}";
        }
        return Orbita.Contracts.CrmTelephonyProviders.Plusofon;
    }

    private static string GetEndpointKey(Guid officeId, string accountKey = "default") =>
        accountKey == "default" ? officeId.ToString("N") : $"{officeId:N}-{accountKey}";

    private static bool IsValidAccountKey(string accountKey) =>
        accountKey.Length is > 0 and <= 16
        && accountKey.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');

    private async Task WriteOutboundSelectionAsync(
        Guid officeId,
        string provider,
        bool useForOutbound,
        CancellationToken ct)
    {
        var path = Path.Combine(_options.ConfigPath, $"outbound.{officeId:D}.conf");
        if (useForOutbound)
        {
            await WriteAtomicallyAsync(path, provider + "\n", ct);
            return;
        }

        if (!File.Exists(path))
        {
            await WriteAtomicallyAsync(path, "primary\n", ct);
            return;
        }

        var current = (await File.ReadAllTextAsync(path, ct)).Trim();
        if (string.Equals(current, provider, StringComparison.OrdinalIgnoreCase))
        {
            await WriteAtomicallyAsync(path, "primary\n", ct);
        }
    }

    private static bool ContainsAsteriskControlCharacter(string value) =>
        value.IndexOfAny(['\r', '\n', ';', '[', ']']) >= 0;

    private async Task WriteAtomicallyAsync(string path, string content, CancellationToken ct)
    {
        var directory = Path.GetDirectoryName(path);
        if (string.IsNullOrWhiteSpace(directory))
        {
            throw new InvalidOperationException("The runtime configuration path must include a directory.");
        }

        Directory.CreateDirectory(directory);
        var writeLock = _writeLocks.GetOrAdd(path, _ => new SemaphoreSlim(1, 1));
        await writeLock.WaitAsync(ct);
        var tempPath = Path.Combine(
            directory,
            $".{Path.GetFileName(path)}.{Guid.NewGuid():N}.tmp");
        try
        {
            await File.WriteAllTextAsync(tempPath, content, new UTF8Encoding(false), ct);
            File.Move(tempPath, path, true);
        }
        finally
        {
            try
            {
                File.Delete(tempPath);
            }
            finally
            {
                writeLock.Release();
            }
        }
    }
}
