using System.Text;
using Microsoft.Extensions.Options;
using Orbita.Api.Options;

namespace Orbita.Api.Services;

public sealed record CrmSipRuntimeAccount(
    string Server,
    string Domain,
    int Port,
    string Transport,
    string SipLogin,
    string AuthorizationLogin,
    string Password,
    bool UseForOutbound,
    string AccountKey = "default",
    string Name = "Основная линия",
    string Mode = "shared");

public sealed record CrmSipRuntimeStatus(string Status, DateTime? CheckedAtUtc);

public sealed record CrmAsteriskRuntimeReceiver(Guid PublicId, string Secret);

public sealed class CrmSipRuntimeConfigWriter(IOptions<CrmSipRuntimeOptions> configuredOptions)
{
    private readonly CrmSipRuntimeOptions _options = configuredOptions.Value;

    public bool IsAvailable => !string.IsNullOrWhiteSpace(_options.ConfigPath);

    public async Task<(bool Success, string? Error)> WriteBeelineAsync(
        Guid officeId,
        CrmSipRuntimeAccount account,
        CancellationToken ct = default) =>
        await WriteBeelineAccountsAsync(officeId, [account with { AccountKey = "default" }], ct);

    public async Task<(bool Success, string? Error)> WriteBeelineAccountsAsync(
        Guid officeId,
        IReadOnlyCollection<CrmSipRuntimeAccount> accounts,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return (false, "Каталог runtime-конфигурации SIP-сервера не настроен.");
        }

        var unsafeValue = accounts.Any(account => new[]
            {
                account.Server,
                account.Domain,
                account.Transport,
                account.SipLogin,
                account.AuthorizationLogin,
                account.Password,
                account.AccountKey
            }.Any(ContainsAsteriskControlCharacter));
        if (unsafeValue)
        {
            return (false, "Реквизиты содержат недопустимые управляющие символы.");
        }

        var officeKey = officeId.ToString("D");
        Directory.CreateDirectory(_options.ConfigPath);
        var configPath = Path.Combine(_options.ConfigPath, $"beeline.{officeKey}.conf");
        var outboundPath = Path.Combine(_options.ConfigPath, $"beeline.{officeKey}.outbound");
        var accountsPath = Path.Combine(_options.ConfigPath, $"beeline.{officeKey}.accounts");
        if (accounts.Any(account => !IsValidAccountKey(account.AccountKey))
            || accounts.GroupBy(account => account.AccountKey, StringComparer.OrdinalIgnoreCase).Any(group => group.Count() > 1))
        {
            return (false, "Идентификаторы SIP-линий некорректны или повторяются.");
        }

        var normalizedAccounts = accounts
            .OrderBy(account => account.AccountKey, StringComparer.Ordinal)
            .ToList();
        var configBuilder = new StringBuilder("; Generated by Orbita. Do not edit inside the container.\n");
        foreach (var account in normalizedAccounts)
        {
            // Server is the regional outbound proxy while Domain is the registrar.
            var endpointKey = GetEndpointKey(officeId, account.AccountKey);
            var registrar = account.Domain;
            var outboundProxy = $"sip:{account.Server}:{account.Port}\\;lr";
            configBuilder.AppendLine($$"""
            ; {{account.Name}} ({{account.Mode}})
            [beeline-{{endpointKey}}-auth]
            type=auth
            auth_type=userpass
            username={{account.AuthorizationLogin}}
            password={{account.Password}}

            [beeline-{{endpointKey}}-aor]
            type=aor
            contact=sip:{{registrar}}:{{account.Port}}
            qualify_frequency=30

            [beeline-{{endpointKey}}]
            type=endpoint
            transport=transport-{{account.Transport}}
            context=from-orbita-provider
            disallow=all
            allow=alaw,ulaw
            outbound_auth=beeline-{{endpointKey}}-auth
            aors=beeline-{{endpointKey}}-aor
            outbound_proxy={{outboundProxy}}
            from_user={{account.SipLogin}}
            from_domain={{account.Domain}}
            direct_media=no
            rtp_symmetric=yes
            force_rport=yes
            rewrite_contact=yes
            dtmf_mode=rfc4733
            set_var=ORBITA_OFFICE_ID={{officeKey}}

            [beeline-{{endpointKey}}-registration]
            type=registration
            transport=transport-{{account.Transport}}
            outbound_auth=beeline-{{endpointKey}}-auth
            outbound_proxy={{outboundProxy}}
            server_uri=sip:{{registrar}}:{{account.Port}}
            client_uri=sip:{{account.SipLogin}}@{{account.Domain}}
            contact_user={{account.SipLogin}}
            line=yes
            endpoint=beeline-{{endpointKey}}
            retry_interval=60
            forbidden_retry_interval=300
            expiration=300
            """);
        }

        var defaultAccount = normalizedAccounts.FirstOrDefault(account => account.UseForOutbound);
        var outboundEndpoint = defaultAccount is null
            ? "primary"
            : defaultAccount.AccountKey == "default"
                ? "beeline"
                : $"beeline-{GetEndpointKey(officeId, defaultAccount.AccountKey)}";
        var accountIndex = string.Join('\n', normalizedAccounts.Select(account =>
            $"{account.AccountKey}=beeline-{GetEndpointKey(officeId, account.AccountKey)}-registration"));
        await WriteAtomicallyAsync(configPath, configBuilder.ToString(), ct);
        await WriteAtomicallyAsync(accountsPath, accountIndex.Length == 0 ? string.Empty : accountIndex + "\n", ct);
        await WriteAtomicallyAsync(outboundPath, outboundEndpoint + "\n", ct);
        return (true, null);
    }

    public async Task<(bool Success, string? Error)> WriteAsteriskReceiverAsync(
        Guid officeId,
        CrmAsteriskRuntimeReceiver receiver,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return (false, "Каталог runtime-конфигурации SIP-сервера не настроен.");
        }
        if (receiver.PublicId == Guid.Empty
            || string.IsNullOrWhiteSpace(receiver.Secret)
            || receiver.Secret.Length > 512
            || receiver.Secret.Any(character => character is '\r' or '\n' or '='))
        {
            return (false, "Некорректные реквизиты приёмника SIP-сервера.");
        }

        Directory.CreateDirectory(_options.ConfigPath);
        var path = Path.Combine(_options.ConfigPath, $"receiver.{officeId:D}.conf");
        var content = $"public_id={receiver.PublicId:D}\nsecret={receiver.Secret}\n";
        await WriteAtomicallyAsync(path, content, ct);
        return (true, null);
    }

    public async Task<CrmSipRuntimeStatus> ReadBeelineStatusAsync(
        Guid officeId,
        string accountKey = "default",
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return new CrmSipRuntimeStatus("runtime-unavailable", null);
        }

        var path = Path.Combine(_options.ConfigPath, $"beeline.{officeId:D}.status");
        if (!File.Exists(path))
        {
            return new CrmSipRuntimeStatus("pending", null);
        }

        try
        {
            var lines = await File.ReadAllLinesAsync(path, ct);
            var statusLine = lines.FirstOrDefault(line => line.StartsWith($"{accountKey}=", StringComparison.OrdinalIgnoreCase));
            var status = statusLine is null
                ? "pending"
                : statusLine[(statusLine.IndexOf('=') + 1)..].Trim().ToLowerInvariant();
            var checkedAtLine = lines.LastOrDefault();
            var checkedAt = lines.Length > 1 && DateTime.TryParse(
                checkedAtLine,
                null,
                System.Globalization.DateTimeStyles.RoundtripKind,
                out var parsed)
                ? parsed.ToUniversalTime()
                : (DateTime?)null;
            return new CrmSipRuntimeStatus(
                string.IsNullOrWhiteSpace(status) ? "unknown" : status,
                checkedAt);
        }
        catch (IOException)
        {
            return new CrmSipRuntimeStatus("pending", null);
        }
    }

    public async Task WriteUserOutboundRoutesAsync(
        Guid officeId,
        IReadOnlyDictionary<string, string> routes,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return;
        }

        Directory.CreateDirectory(_options.ConfigPath);
        var path = Path.Combine(_options.ConfigPath, $"routes.{officeId:D}.conf");
        var content = string.Join(
            '\n',
            routes
                .Where(x => x.Key.Length is > 0 and <= 8 && x.Key.All(char.IsDigit))
                .OrderBy(x => x.Key, StringComparer.Ordinal)
                .Select(x => $"{x.Key}={NormalizeOutboundProvider(officeId, x.Value)}"));
        await WriteAtomicallyAsync(path, content.Length == 0 ? string.Empty : content + "\n", ct);
    }

    private static string NormalizeOutboundProvider(Guid officeId, string? provider)
    {
        if (string.Equals(provider, Orbita.Contracts.CrmTelephonyProviders.Beeline, StringComparison.OrdinalIgnoreCase))
        {
            return Orbita.Contracts.CrmTelephonyProviders.Beeline;
        }
        if (Orbita.Contracts.CrmTelephonyOutboundProviders.TryGetBeelineLineKey(provider, out var accountKey))
        {
            // The original single Beeline account is stored as `default` and its
            // Asterisk endpoint keeps the legacy office-scoped name.  Preserve
            // the legacy route token so the watcher resolves it correctly.
            if (string.Equals(accountKey, "default", StringComparison.OrdinalIgnoreCase))
            {
                return Orbita.Contracts.CrmTelephonyProviders.Beeline;
            }
            return $"beeline-{GetEndpointKey(officeId, accountKey)}";
        }
        return Orbita.Contracts.CrmTelephonyProviders.Plusofon;
    }

    private static string GetEndpointKey(Guid officeId, string accountKey = "default") =>
        accountKey == "default" ? officeId.ToString("N") : $"{officeId:N}-{accountKey}";

    private static bool IsValidAccountKey(string accountKey) =>
        accountKey.Length is > 0 and <= 16
        && accountKey.All(character => char.IsAsciiLetterOrDigit(character) || character is '-' or '_');

    private static bool ContainsAsteriskControlCharacter(string value) =>
        value.IndexOfAny(['\r', '\n', ';', '[', ']']) >= 0;

    private static async Task WriteAtomicallyAsync(string path, string content, CancellationToken ct)
    {
        var tempPath = path + ".tmp";
        await File.WriteAllTextAsync(tempPath, content, new UTF8Encoding(false), ct);
        File.Move(tempPath, path, true);
    }
}
