using System.Text;
using Microsoft.Extensions.Options;
using Orbita.Api.Options;

namespace Orbita.Api.Services;

public sealed record CrmSipRuntimeAccount(
    string Server,
    string Domain,
    int Port,
    string Transport,
    string SipLogin,
    string AuthorizationLogin,
    string Password,
    bool UseForOutbound);

public sealed record CrmSipRuntimeStatus(string Status, DateTime? CheckedAtUtc);

public sealed record CrmAsteriskRuntimeReceiver(Guid PublicId, string Secret);

public sealed class CrmSipRuntimeConfigWriter(IOptions<CrmSipRuntimeOptions> configuredOptions)
{
    private readonly CrmSipRuntimeOptions _options = configuredOptions.Value;

    public bool IsAvailable => !string.IsNullOrWhiteSpace(_options.ConfigPath);

    public async Task<(bool Success, string? Error)> WriteBeelineAsync(
        Guid officeId,
        CrmSipRuntimeAccount account,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return (false, "Каталог runtime-конфигурации SIP-сервера не настроен.");
        }

        var unsafeValue = new[]
        {
            account.Server,
            account.Domain,
            account.Transport,
            account.SipLogin,
            account.AuthorizationLogin,
            account.Password
        }.Any(ContainsAsteriskControlCharacter);
        if (unsafeValue)
        {
            return (false, "Реквизиты содержат недопустимые управляющие символы.");
        }

        var officeKey = officeId.ToString("D");
        var endpointKey = GetEndpointKey(officeId);
        Directory.CreateDirectory(_options.ConfigPath);
        var configPath = Path.Combine(_options.ConfigPath, $"beeline.{officeKey}.conf");
        var outboundPath = Path.Combine(_options.ConfigPath, $"beeline.{officeKey}.outbound");
        // In the Beeline form Server is the regional outbound proxy
        // (for example ekt.ip.beeline.ru), while Domain is the registrar
        // advertised by Beeline (ip.beeline.ru).  These addresses are not
        // interchangeable: REGISTER must target the registrar and travel
        // through the proxy.
        var registrar = account.Domain;
        var outboundProxy = $"sip:{account.Server}:{account.Port}\\;lr";
        var config = $$"""
            ; Generated by Orbita. Do not edit inside the container.
            [beeline-{{endpointKey}}-auth]
            type=auth
            auth_type=userpass
            username={{account.AuthorizationLogin}}
            password={{account.Password}}

            [beeline-{{endpointKey}}-aor]
            type=aor
            contact=sip:{{registrar}}:{{account.Port}}
            qualify_frequency=30

            [beeline-{{endpointKey}}]
            type=endpoint
            transport=transport-{{account.Transport}}
            context=from-orbita-provider
            disallow=all
            allow=alaw,ulaw
            outbound_auth=beeline-{{endpointKey}}-auth
            aors=beeline-{{endpointKey}}-aor
            outbound_proxy={{outboundProxy}}
            from_user={{account.SipLogin}}
            from_domain={{account.Domain}}
            direct_media=no
            rtp_symmetric=yes
            force_rport=yes
            rewrite_contact=yes
            dtmf_mode=rfc4733
            set_var=ORBITA_OFFICE_ID={{officeKey}}

            [beeline-{{endpointKey}}-identify]
            type=identify
            endpoint=beeline-{{endpointKey}}
            match={{account.Server}}

            [beeline-{{endpointKey}}-registration]
            type=registration
            transport=transport-{{account.Transport}}
            outbound_auth=beeline-{{endpointKey}}-auth
            outbound_proxy={{outboundProxy}}
            server_uri=sip:{{registrar}}:{{account.Port}}
            client_uri=sip:{{account.SipLogin}}@{{account.Domain}}
            contact_user={{account.SipLogin}}
            retry_interval=60
            forbidden_retry_interval=300
            expiration=300
            """;

        await WriteAtomicallyAsync(configPath, config + Environment.NewLine, ct);
        await WriteAtomicallyAsync(outboundPath, account.UseForOutbound ? "beeline\n" : "primary\n", ct);
        return (true, null);
    }

    public async Task<(bool Success, string? Error)> WriteAsteriskReceiverAsync(
        Guid officeId,
        CrmAsteriskRuntimeReceiver receiver,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return (false, "Каталог runtime-конфигурации SIP-сервера не настроен.");
        }
        if (receiver.PublicId == Guid.Empty
            || string.IsNullOrWhiteSpace(receiver.Secret)
            || receiver.Secret.Length > 512
            || receiver.Secret.Any(character => character is '\r' or '\n' or '='))
        {
            return (false, "Некорректные реквизиты приёмника SIP-сервера.");
        }

        Directory.CreateDirectory(_options.ConfigPath);
        var path = Path.Combine(_options.ConfigPath, $"receiver.{officeId:D}.conf");
        var content = $"public_id={receiver.PublicId:D}\nsecret={receiver.Secret}\n";
        await WriteAtomicallyAsync(path, content, ct);
        return (true, null);
    }

    public async Task<CrmSipRuntimeStatus> ReadBeelineStatusAsync(
        Guid officeId,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return new CrmSipRuntimeStatus("runtime-unavailable", null);
        }

        var path = Path.Combine(_options.ConfigPath, $"beeline.{officeId:D}.status");
        if (!File.Exists(path))
        {
            return new CrmSipRuntimeStatus("pending", null);
        }

        try
        {
            var lines = await File.ReadAllLinesAsync(path, ct);
            var status = lines.FirstOrDefault()?.Trim().ToLowerInvariant();
            var checkedAt = lines.Length > 1 && DateTime.TryParse(
                lines[1],
                null,
                System.Globalization.DateTimeStyles.RoundtripKind,
                out var parsed)
                ? parsed.ToUniversalTime()
                : (DateTime?)null;
            return new CrmSipRuntimeStatus(
                string.IsNullOrWhiteSpace(status) ? "unknown" : status,
                checkedAt);
        }
        catch (IOException)
        {
            return new CrmSipRuntimeStatus("pending", null);
        }
    }

    public async Task WriteUserOutboundRoutesAsync(
        Guid officeId,
        IReadOnlyDictionary<string, string> routes,
        CancellationToken ct = default)
    {
        if (!IsAvailable)
        {
            return;
        }

        Directory.CreateDirectory(_options.ConfigPath);
        var path = Path.Combine(_options.ConfigPath, $"routes.{officeId:D}.conf");
        var content = string.Join(
            '\n',
            routes
                .Where(x => x.Key.Length is > 0 and <= 8 && x.Key.All(char.IsDigit))
                .OrderBy(x => x.Key, StringComparer.Ordinal)
                .Select(x => $"{x.Key}={NormalizeOutboundProvider(x.Value)}"));
        await WriteAtomicallyAsync(path, content.Length == 0 ? string.Empty : content + "\n", ct);
    }

    private static string NormalizeOutboundProvider(string? provider) =>
        string.Equals(provider, Orbita.Contracts.CrmTelephonyProviders.Beeline, StringComparison.OrdinalIgnoreCase)
            ? Orbita.Contracts.CrmTelephonyProviders.Beeline
            : Orbita.Contracts.CrmTelephonyProviders.Plusofon;

    private static string GetEndpointKey(Guid officeId) => officeId.ToString("N");

    private static bool ContainsAsteriskControlCharacter(string value) =>
        value.IndexOfAny(['\r', '\n', ';', '[', ']']) >= 0;

    private static async Task WriteAtomicallyAsync(string path, string content, CancellationToken ct)
    {
        var tempPath = path + ".tmp";
        await File.WriteAllTextAsync(tempPath, content, new UTF8Encoding(false), ct);
        File.Move(tempPath, path, true);
    }
}
