namespace Orbita.Contracts;

public sealed record GlobalDashboardSummary(
    int TotalWorkers,
    int OnlineWorkers,
    int TotalToday,
    int SentToCrm,
    int InProgress,
    int Duplicates,
    int Errors,
    int ActionRequired,
    int ConnectedAccounts,
    int RequiresAuthorization,
    int AccountsNeedAttentionCount,
    int ActiveAdsCount,
    int BlockedAdsCount,
    decimal TotalBalance,
    IReadOnlyList<ActivityPointDto> HourlyActivity,
    IReadOnlyList<ActivityPointDto> WeeklyByDayActivity,
    DateTime AggregatedAtUtc);

public sealed record WorkerListItem(
    Guid Id,
    string DisplayName,
    string MachineName,
    string AppVersion,
    string MonitoringStatus,
    string? MonitoringStatusMessage,
    bool IsMonitoringActive,
    bool IsOnline,
    DateTime? LastSeenAtUtc,
    int AccountCount,
    int TotalToday,
    int Errors,
    bool UpdateAvailable = false,
    string? LatestReleaseVersion = null,
    Guid OfficeId = default,
    string OfficeName = "");

public sealed record WorkerDetail(
    Guid Id,
    string DisplayName,
    string MachineName,
    string AppVersion,
    string MonitoringStatus,
    string? MonitoringStatusMessage,
    bool IsMonitoringActive,
    bool IsOnline,
    DateTime? LastSeenAtUtc,
    DateTime? NextCycleCheckAtUtc,
    DashboardStatsDto? LatestStats,
    IReadOnlyList<WorkerBalanceDto> Balances,
    int MaxConcurrentAccounts = 1,
    double? LastCpuPercent = null,
    double? LastRamPercent = null,
    long? LastRamUsedMb = null,
    long? LastRamTotalMb = null,
    string? IpAddress = null,
    string? OperatingSystem = null,
    DateTime? StartedAtUtc = null,
    string? AgentVersion = null,
    string? AdsPowerApiBaseUrl = null,
    string? AdsPowerApiKey = null);

public sealed record WorkerEventListItem(
    Guid Id,
    Guid WorkerId,
    string WorkerDisplayName,
    Guid? AccountId,
    string Level,
    string Message,
    string? Details,
    DateTime CreatedAtUtc);