namespace Orbita.Contracts;

public sealed record DashboardAccountStatusCounts(
    int Active,
    int Inactive,
    int Blocked,
    int Errors);

public sealed record GlobalDashboardSummary(
    int TotalWorkers,
    int OnlineWorkers,
    int TotalToday,
    int SentToCrm,
    int InProgress,
    int Duplicates,
    int Errors,
    int ActionRequired,
    int ConnectedAccounts,
    int RequiresAuthorization,
    int AccountsNeedAttentionCount,
    DashboardAccountStatusCounts AccountStatusCounts,
    int ActiveAdsCount,
    int BlockedAdsCount,
    decimal TotalBalance,
    IReadOnlyList<ActivityPointDto> HourlyActivity,
    IReadOnlyList<ActivityPointDto> WeeklyByDayActivity,
    DateTime AggregatedAtUtc);

public sealed record WorkerListItem(
    Guid Id,
    string DisplayName,
    string MachineName,
    string AppVersion,
    string MonitoringStatus,
    string? MonitoringStatusMessage,
    bool IsMonitoringActive,
    bool IsOnline,
    DateTime? LastSeenAtUtc,
    int AccountCount,
    int TotalToday,
    int DuplicatesToday,
    int Errors,
    bool UpdateAvailable = false,
    string? LatestReleaseVersion = null,
    Guid OfficeId = default,
    string OfficeName = "",
    bool IsEnabled = true,
    int ActiveAccountCount = 0,
    WorkerActivityDto? CurrentActivity = null,
    IReadOnlyList<WorkerActiveAccountDto>? ActiveAccounts = null);

public sealed record WorkerDetail(
    Guid Id,
    string DisplayName,
    string MachineName,
    string AppVersion,
    string MonitoringStatus,
    string? MonitoringStatusMessage,
    bool IsMonitoringActive,
    bool IsOnline,
    DateTime? LastSeenAtUtc,
    DateTime? NextCycleCheckAtUtc,
    DashboardStatsDto? LatestStats,
    IReadOnlyList<WorkerBalanceDto> Balances,
    int MaxConcurrentAccounts = 1,
    double? LastCpuPercent = null,
    double? LastRamPercent = null,
    long? LastRamUsedMb = null,
    long? LastRamTotalMb = null,
    string? IpAddress = null,
    string? OperatingSystem = null,
    DateTime? StartedAtUtc = null,
    string? AgentVersion = null,
    string? AdsPowerApiBaseUrl = null,
    string? AdsPowerApiKey = null,
    bool IsEnabled = true,
    int TodayResponses = 0,
    int TodayDuplicates = 0,
    int TodayErrors = 0,
    int ActiveAccountCount = 0,
    int TotalAccountCount = 0,
    WorkerActivityDto? CurrentActivity = null,
    IReadOnlyList<WorkerActiveAccountDto>? ActiveAccounts = null,
    bool ResponseFilterEnabled = false,
    bool ResponseFilterExcludeFemale = false,
    int? ResponseFilterMaxAge = null,
    bool ResponseFilterExcludeMale = false,
    int? ResponseFilterMaxAgeMale = null,
    int? ResponseFilterMaxAgeFemale = null,
    int? ResponseFilterMaxResponseAgeDays = null,
    bool ResponseHighlightEnabled = false,
    string? ResponseHighlightAgeBuckets = null,
    bool AutoScheduleEnabled = false,
    string? AutoScheduleDays = null,
    string? AutoScheduleFromLocalTime = null,
    string? AutoScheduleToLocalTime = null,
    bool MessengerAutoReplyEnabled = false,
    string? MessengerAutoReplyMessage = null,
    int? PhoneUnchangedHours = null,
    bool AutoDeliverToCrm = false,
    bool AutoDeliverToBitrix = true,
    Guid OfficeId = default,
    string OfficeName = "",
    string? ResponseHighlightTargetsJson = null);

public sealed record WorkerEventListItem(
    Guid Id,
    Guid WorkerId,
    string WorkerDisplayName,
    Guid? AccountId,
    string? AccountDisplayName,
    string Level,
    string Message,
    string? Details,
    DateTime CreatedAtUtc);
