FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY Orbita.Contracts/*.csproj Orbita.Contracts/
COPY Orbita.Logging/*.csproj Orbita.Logging/
COPY Orbita.Web/*.csproj Orbita.Web/
RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet restore Orbita.Web/Orbita.Web.csproj

COPY Orbita.Contracts/ Orbita.Contracts/
COPY Orbita.Logging/ Orbita.Logging/
COPY Orbita.Web/ Orbita.Web/
RUN --mount=type=cache,target=/root/.nuget/packages \
    dotnet publish Orbita.Web/Orbita.Web.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "Orbita.Web.dll"]